package sg.gov.csit.opvamspv.paymentvoucher;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;
import java.util.List;

/**
 * Claim form XML document generated by SAP.
 */
@XmlRootElement(name = "claim_form", namespace = "http://www.did.gov.sg/ivc")
final class XmlClaimForm {
    @XmlElement(namespace = "http://www.did.gov.sg/ivc")
    Header header;

    @XmlElement(namespace = "http://www.did.gov.sg/ivc")
    Basic basic;

    @XmlElement(namespace = "http://www.did.gov.sg/ivc")
    Calculation calculation;

    @XmlElementWrapper(namespace = "http://www.did.gov.sg/ivc", name = "item_list")
    @XmlElement(name = "item")
    List<Item> items;

    static final class Basic {
        @XmlElement(name = "requestor_name")
        String requestorName;
        @XmlElement(name = "station")
        String station;
        @XmlElement(name = "pv_date")
        String pvDate;
        @XmlElement(name = "payee")
        String payee;
        @XmlElement(name = "reference_number")
        String referenceNumber;
        @XmlElement(name = "reference_date")
        String referenceDate;
        @XmlElement(name = "payment_method")
        String paymentMethod;
        @XmlElement(name = "housebank")
        String housebank;
        @XmlElement(name = "description")
        String description;
        @XmlElement(name = "main_description")
        String mainDescription;
        @XmlElement(name = "company_code")
        String companyCode;
        @XmlElement(name = "tax_code")
        String taxCode;
    }

    static final class Calculation {
        @XmlElement(name = "currency")
        String currency;
        @XmlElement(name = "currency_rate")
        BigDecimal currencyRate;
        @XmlElement(name = "withhold_tax_base_amt")
        BigDecimal withholdTaxBaseAmt;
        @XmlElement(name = "total_tax")
        BigDecimal totalTax;
        @XmlElement(name = "total_amount")
        BigDecimal totalAmount;
        @XmlElement(name = "total_amount_local")
        BigDecimal totalAmountLocal;
        @XmlElement(name = "pfms_doc_type")
        String pfmsDocType;
    }

    static final class Header {
        @XmlElement(name = "pv_form_id")
        String pvFormId;
    }

    static final class Item {
        @XmlElement(name = "item_desc")
        String desc;
        @XmlElement(name = "item_receipt_number")
        String receiptNo;
        @XmlElement(name = "item_receipt_date")
        String receiptDate;
        @XmlElement(name = "item_amount_no_tax")
        BigDecimal amountNoTax;
        @XmlElement(name = "item_extra_charges")
        BigDecimal extraCharges;
        @XmlElement(name = "item_tax_code")
        String taxCode;
        @XmlElement(name = "item_tax")
        double tax;
        @XmlElement(name = "item_amount_w_tax")
        double amountWithTax;
        @XmlElement(name = "item_agency_code")
        String agencyCode;
        @XmlElement(name = "item_project")
        String project;
        @XmlElement(name = "item_cost_centre")
        String costCentre;
        @XmlElement(name = "item_fund_centre")
        String fundCentre;
        @XmlElement(name = "item_prepayment_period_from")
        String prepaymentPeriodFrom;
        @XmlElement(name = "item_prepayment_period_to")
        String prepaymentPeriodTo;
        @XmlElement(name = "item_gl_account")
        String glAccount;
        @XmlElement(name = "item_fund_number")
        String fundNumber;
        @XmlElement(name = "item_country")
        String country;
        @XmlElement(name = "item_assignment")
        String assignment;
        @XmlElement(name = "item_fixed_asset_indicator")
        char fixedAssetIndicator; // Could be boolean?
        @XmlElement(name = "item_transaction_type")
        String transactionType;
        @XmlElement(name = "item_fixed_asset_number")
        String fixedAssetNo;
        @XmlElement(name = "item_units_of_fixed_asset")
        String unitsOfFixedAsset;
        @XmlElement(name = "item_ct_indicator")
        String ctIndicator;
        @XmlElement(name = "item_mo_indicator")
        String moIndicator;
    }
}
